AllCops:
  TargetRubyVersion: 3.2

  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
  Enabled: true

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'app/helpers/admin_menu_helper.rb'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'lib/tasks/*.rake'

Metrics/AbcSize:
  Max: 23
  Exclude:
    - 'app/helpers/admin_menu_helper.rb'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/DoubleNegation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude:
    - 'test/services/email_template_renderer_test.rb'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/FormatString:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolLiteral:
  Enabled: false

Lint/FormatParameterMismatch:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Bundler/OrderedGems:
  Enabled: false

Security/YAMLLoad:
  Exclude:
    - 'test/**/*'

Style/EmptyMethod:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

