AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120
  Enabled: true

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'app/helpers/admin_menu_helper.rb'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Style/SignalException:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/FormatString:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
